using System;

// Math.Sin is [Intrinsic] + InternalCall in CoreCLR: it has no IL body, and the JIT lowers it
// to a call into the platform C library's `sin`. PawPrint implements it in-tree instead
// (DeterministicMath.sin), so that a replay cannot depend on which libm the recording machine
// had.
//
// This file runs under both PawPrint and the real runtime and the two exit codes are compared,
// so it may only assert things *both* must agree on. `sin` is not correctly rounded and the two
// implementations differ by one ulp on inputs near a midpoint (PawPrint is the nearer
// of the two there, but that is not something this test can assert against a runtime whose
// answer it cannot predict). So nothing below pins a last bit that is not forced: the assertions
// are the special cases IEEE 754 fixes exactly, values whose correctly rounded result is the
// same under any implementation within an ulp of the truth, and identities that hold of the real
// sine and so must hold of any faithful approximation to within a slack far wider than an ulp.
//
// The one place IEEE 754 leaves open is the payload of a NaN, whether generated by the
// domain error at an infinite argument or propagated from a NaN one: hosts differ on both the
// payload and the sign. So the NaN cases below check double.IsNaN and never the bits.
//
// The bit-exact specification of PawPrint's own answer, including the NaN payloads, lives in
// TestDeterministicMath.fs, which can assert it because it is not comparing against a host.
public static class MathSin
{
    // A spread of arguments covering every regime of the range reduction: below a quarter turn,
    // a few turns, and magnitudes at which no amount of double arithmetic can reduce the
    // argument and a multi-hundred-bit value of pi is the only way through.
    static readonly double[] Arguments =
    {
        0.0, 1e-300, 1e-30, 1e-8, 0.25, 0.5, 1.0, 1.5, 2.0, 3.0, 3.5, 6.0, 7.0,
        11.0, 123.456, 1000.0, 12345.6789, 1e5, 1e8, 1e10, 1e15, 1e20, 1e30,
        1e50, 1e100, 1e200, 1e300,
    };

    static int ExactCases()
    {
        // IEEE 754-2019 clause 9.2.1: "For the operations sin, tan, ... f(+0) is +0 and f(-0)
        // is -0 with no exception." The sign of the zero is specified, so unlike the sign of a
        // NaN it can be asserted against a host.
        if (Math.Sin(0.0) != 0.0) return 1;
        if (double.IsNegative(Math.Sin(0.0))) return 2;
        if (Math.Sin(-0.0) != 0.0) return 3;
        if (!double.IsNegative(Math.Sin(-0.0))) return 4;

        // sin(x) is exactly x for an x small enough that x - x^3/6 is nearer to x than to
        // either of its neighbours: that needs x^2/6 below 2^-53, i.e. |x| below about 2^-25.
        if (Math.Sin(1e-30) != 1e-30) return 5;
        if (Math.Sin(-1e-30) != -1e-30) return 6;
        if (Math.Sin(1e-300) != 1e-300) return 7;
        if (Math.Sin(double.Epsilon) != double.Epsilon) return 8;
        if (Math.Sin(-double.Epsilon) != -double.Epsilon) return 9;

        return 0;
    }

    static int NaNRules()
    {
        // An infinite argument names no point on the circle: a domain error.
        if (!double.IsNaN(Math.Sin(double.PositiveInfinity))) return 1;
        if (!double.IsNaN(Math.Sin(double.NegativeInfinity))) return 2;

        // NaN propagates.
        if (!double.IsNaN(Math.Sin(double.NaN))) return 3;

        return 0;
    }

    static int StaysInRange()
    {
        for (int i = 0; i < Arguments.Length; i++)
        {
            double x = Arguments[i];
            double s = Math.Sin(x);

            if (double.IsNaN(s)) return 100 + i;
            if (s < -1.0 || s > 1.0) return 200 + i;

            // Oddness is required of the operation, not just of the real function it
            // approximates: IEEE 754-2019 clause 9.2 says so for roundTiesToEven, which is
            // what both runtimes use. (Its evenness rule for cos is the stronger one, holding
            // under every rounding attribute; oddness is only guaranteed under the three
            // round-to-nearest-or-zero attributes.) So both runtimes owe this exactly, not to
            // within an ulp.
            if (Math.Sin(-x) != -s) return 300 + i;
        }

        return 0;
    }

    static int PythagoreanIdentity()
    {
        // sin^2 + cos^2 = 1 everywhere. This is the check that ties the two functions'
        // quadrant tables together: they share a range reduction and differ only in which
        // residues call for the sine and which of them negate, so an implementation that
        // rotated one table relative to the other would still be bounded and still have the
        // right parity, but would fail this immediately.
        for (int i = 0; i < Arguments.Length; i++)
        {
            double x = Arguments[i];
            double s = Math.Sin(x);
            double c = Math.Cos(x);

            if (Math.Abs(s * s + c * c - 1.0) > 1e-12) return 100 + i;
        }

        return 0;
    }

    static int DoubleAngleIdentity()
    {
        // sin(2x) = 2 sin(x) cos(x) holds of the real functions, so it must hold of any
        // faithful approximation to within a few ulps -- and doubling an argument is exact in
        // binary floating point, so the two sides really are the same real number.
        //
        // This is the strongest check available here, because it is the range reduction that
        // it tests: getting sin(1e20) right and sin(2e20) right *consistently* requires both
        // reductions to be against the same several-hundred-bit value of pi. An implementation
        // that reduced in double arithmetic would produce two unrelated numbers and fail by a
        // margin of order 1, not of order an ulp.
        for (int i = 0; i < Arguments.Length; i++)
        {
            // Every entry of Arguments is below 1e301, so 2x is representable throughout.
            double x = Arguments[i];
            double doubled = Math.Sin(2.0 * x);

            if (Math.Abs(doubled - 2.0 * Math.Sin(x) * Math.Cos(x)) > 1e-12) return 100 + i;
        }

        return 0;
    }

    static int IncreasesOverTheFirstQuarterTurn()
    {
        // sin is strictly increasing on [0, pi/2], and these samples are spaced far enough
        // apart that a one-ulp disagreement between implementations cannot reorder them.
        double previous = -2.0;

        for (int i = 0; i <= 32; i++)
        {
            double x = 1.5707963267948966 * i / 32.0;
            double s = Math.Sin(x);

            if (s <= previous) return 100 + i;

            previous = s;
        }

        // ...and it has come essentially all the way up to 1 by the end.
        if (previous < 0.999) return 1;

        return 0;
    }

    public static int Main(string[] args)
    {
        int result;

        result = ExactCases();
        if (result != 0) return 1000 + result;

        result = NaNRules();
        if (result != 0) return 2000 + result;

        result = StaysInRange();
        if (result != 0) return 3000 + result;

        result = PythagoreanIdentity();
        if (result != 0) return 4000 + result;

        result = DoubleAngleIdentity();
        if (result != 0) return 5000 + result;

        result = IncreasesOverTheFirstQuarterTurn();
        if (result != 0) return 6000 + result;

        return 0;
    }
}
