using System;

// Math.Pow is [Intrinsic] + InternalCall in CoreCLR: it has no IL body, and the JIT lowers it
// to a call into the platform C library's `pow`. PawPrint implements it in-tree instead
// (DeterministicMath.pow), so that a replay cannot depend on which libm the recording machine
// had.
//
// This file runs under both PawPrint and the real runtime and the two exit codes are compared,
// so it may only assert things *both* must agree on. That rules out any result whose last bit
// depends on the libm: `pow` is not correctly rounded, and PawPrint's implementation and the
// host's genuinely differ by one ulp on inputs that sit near a midpoint (PawPrint is the nearer
// of the two there, but "nearer" is not something this test can assert against a runtime whose
// answer it cannot predict). Every case below is therefore one where the exact mathematical
// result is a representable double, so every correct implementation must return it bit-for-bit,
// or one the IEEE 754 special-case rules pin down exactly.
//
// The one place IEEE 754 leaves genuinely open is the payload of a NaN generated by a domain
// error: x86 hardware produces the negative quiet NaN and Arm the positive one, and the real
// runtime inherits whichever the host has. So the NaN cases below check double.IsNaN and never
// the bits.
public static class MathPow
{
    static int ExactPowers()
    {
        // Powers of two are exact under any correct implementation: log2 of the base is an
        // integer, so there is nothing to round.
        if (Math.Pow(2.0, 10.0) != 1024.0) return 1;
        if (Math.Pow(2.0, 0.0) != 1.0) return 2;
        if (Math.Pow(2.0, -3.0) != 0.125) return 3;
        if (Math.Pow(0.5, 3.0) != 0.125) return 4;
        if (Math.Pow(2.0, 52.0) != 4503599627370496.0) return 5;
        if (Math.Pow(2.0, -1074.0) != double.Epsilon) return 6;
        if (Math.Pow(2.0, 1023.0) != 8.98846567431158E+307) return 7;

        // Small integer powers of small integers: the exact value is representable.
        if (Math.Pow(3.0, 2.0) != 9.0) return 10;
        if (Math.Pow(3.0, 5.0) != 243.0) return 11;
        if (Math.Pow(10.0, 15.0) != 1000000000000000.0) return 12;
        if (Math.Pow(7.0, 3.0) != 343.0) return 13;
        if (Math.Pow(-2.0, 3.0) != -8.0) return 14;
        if (Math.Pow(-2.0, 2.0) != 4.0) return 15;
        if (Math.Pow(-3.0, 5.0) != -243.0) return 16;
        if (Math.Pow(-1.0, 101.0) != -1.0) return 17;
        if (Math.Pow(-1.0, 100.0) != 1.0) return 18;

        // Roots whose exact value is representable, so every correct implementation returns
        // them bit-for-bit. (The stronger statement -- that x^0.5 equals Math.Sqrt(x) for
        // *every* x, which holds because IEEE 754 mandates a correctly rounded sqrt -- is
        // asserted as a property in TestDeterministicMath.fs instead. It cannot be checked
        // from here: Math.Sqrt is itself an unimplemented JIT intrinsic, and implementing it
        // is a separate change.)
        if (Math.Pow(9.0, 0.5) != 3.0) return 20;
        if (Math.Pow(2.25, 0.5) != 1.5) return 21;
        if (Math.Pow(6.25, 0.5) != 2.5) return 22;
        if (Math.Pow(16.0, 0.5) != 4.0) return 23;
        if (Math.Pow(256.0, 0.25) != 4.0) return 24;
        if (Math.Pow(0.25, 0.5) != 0.5) return 25;

        // Overflow and underflow of the ordinary path.
        if (!double.IsPositiveInfinity(Math.Pow(10.0, 400.0))) return 30;
        if (Math.Pow(10.0, -400.0) != 0.0) return 31;
        if (!double.IsPositiveInfinity(Math.Pow(2.0, 1024.0))) return 32;
        if (Math.Pow(2.0, -1075.0) != 0.0) return 33;

        return 0;
    }

    static int ZeroAndOneRules()
    {
        // Anything to the zeroth power is 1, including NaN and the infinities.
        if (Math.Pow(double.NaN, 0.0) != 1.0) return 1;
        if (Math.Pow(double.NaN, -0.0) != 1.0) return 2;
        if (Math.Pow(0.0, 0.0) != 1.0) return 3;
        if (Math.Pow(double.PositiveInfinity, 0.0) != 1.0) return 4;
        if (Math.Pow(-3.5, 0.0) != 1.0) return 5;

        // 1 to any power is 1, including NaN and the infinities.
        if (Math.Pow(1.0, double.NaN) != 1.0) return 10;
        if (Math.Pow(1.0, double.PositiveInfinity) != 1.0) return 11;
        if (Math.Pow(1.0, double.NegativeInfinity) != 1.0) return 12;

        // |x| = 1 with an infinite exponent is 1, not NaN.
        if (Math.Pow(-1.0, double.PositiveInfinity) != 1.0) return 20;
        if (Math.Pow(-1.0, double.NegativeInfinity) != 1.0) return 21;

        return 0;
    }

    static int NaNRules()
    {
        // NaN propagates everywhere the two rules above do not override it.
        if (!double.IsNaN(Math.Pow(double.NaN, 2.0))) return 1;
        if (!double.IsNaN(Math.Pow(2.0, double.NaN))) return 2;
        if (!double.IsNaN(Math.Pow(-1.0, double.NaN))) return 3;

        // A negative base has no real non-integer power.
        if (!double.IsNaN(Math.Pow(-2.0, 0.5))) return 10;
        if (!double.IsNaN(Math.Pow(-2.0, 1.5))) return 11;
        if (!double.IsNaN(Math.Pow(-0.5, -0.5))) return 12;

        return 0;
    }

    static int SignedZeroAndInfinityRules()
    {
        // A zero or infinite base keeps its sign only for an odd integer exponent.
        if (!double.IsPositiveInfinity(Math.Pow(0.0, -1.0))) return 1;
        if (!double.IsNegativeInfinity(Math.Pow(-0.0, -1.0))) return 2;
        if (!double.IsPositiveInfinity(Math.Pow(-0.0, -2.0))) return 3;
        if (!double.IsNegativeInfinity(Math.Pow(-0.0, -3.0))) return 4;

        if (!double.IsPositiveInfinity(1.0 / Math.Pow(0.0, 1.0))) return 10;
        if (!double.IsNegativeInfinity(1.0 / Math.Pow(-0.0, 1.0))) return 11;
        if (!double.IsPositiveInfinity(1.0 / Math.Pow(-0.0, 2.0))) return 12;
        if (!double.IsNegativeInfinity(1.0 / Math.Pow(-0.0, 3.0))) return 13;

        if (!double.IsPositiveInfinity(Math.Pow(double.PositiveInfinity, 1.0))) return 20;
        if (Math.Pow(double.PositiveInfinity, -1.0) != 0.0) return 21;
        if (!double.IsNegativeInfinity(Math.Pow(double.NegativeInfinity, 1.0))) return 22;
        if (!double.IsPositiveInfinity(Math.Pow(double.NegativeInfinity, 2.0))) return 23;
        if (!double.IsNegativeInfinity(Math.Pow(double.NegativeInfinity, 3.0))) return 24;
        if (!double.IsPositiveInfinity(Math.Pow(double.NegativeInfinity, 0.5))) return 25;
        if (!double.IsNegativeInfinity(1.0 / Math.Pow(double.NegativeInfinity, -1.0))) return 26;
        if (!double.IsPositiveInfinity(1.0 / Math.Pow(double.NegativeInfinity, -2.0))) return 27;

        // An infinite exponent: which way it goes depends only on whether |x| exceeds 1.
        if (Math.Pow(0.5, double.PositiveInfinity) != 0.0) return 30;
        if (!double.IsPositiveInfinity(Math.Pow(0.5, double.NegativeInfinity))) return 31;
        if (!double.IsPositiveInfinity(Math.Pow(2.0, double.PositiveInfinity))) return 32;
        if (Math.Pow(2.0, double.NegativeInfinity) != 0.0) return 33;
        if (Math.Pow(0.0, double.PositiveInfinity) != 0.0) return 34;
        if (!double.IsPositiveInfinity(Math.Pow(0.0, double.NegativeInfinity))) return 35;

        return 0;
    }

    static int AgreesWithRepeatedMultiplication()
    {
        // For a base that is an exactly representable small integer and an exponent small
        // enough that the product never needs rounding, repeated multiplication is an exact
        // reference every implementation must match.
        for (int b = 2; b <= 5; b++)
        {
            double product = 1.0;

            for (int n = 0; n <= 20; n++)
            {
                // Stop once the exact product no longer fits in a double's 53 bits, since
                // beyond that the reference stops being exact.
                if (product > 4503599627370496.0) break;

                if (Math.Pow(b, n) != product) return 100 * b + n;
                if (Math.Pow(-b, n) != ((n % 2 == 0) ? product : -product)) return 1000 + 100 * b + n;

                product *= b;
            }
        }

        return 0;
    }

    public static int Main(string[] args)
    {
        int result;

        result = ExactPowers();
        if (result != 0) return 1000 + result;

        result = ZeroAndOneRules();
        if (result != 0) return 2000 + result;

        result = NaNRules();
        if (result != 0) return 3000 + result;

        result = SignedZeroAndInfinityRules();
        if (result != 0) return 4000 + result;

        result = AgreesWithRepeatedMultiplication();
        if (result != 0) return 5000 + result;

        return 0;
    }
}
