using System;

// Math.Cos is [Intrinsic] + InternalCall in CoreCLR: it has no IL body, and the JIT lowers it
// to a call into the platform C library's `cos`. PawPrint implements it in-tree instead
// (DeterministicMath.cos), so that a replay cannot depend on which libm the recording machine
// had.
//
// This file runs under both PawPrint and the real runtime and the two exit codes are compared,
// so it may only assert things *both* must agree on. `cos` is not correctly rounded and the two
// implementations genuinely differ by one ulp on inputs near a midpoint (PawPrint is the nearer
// of the two there, but that is not something this test can assert against a runtime whose
// answer it cannot predict). So nothing below pins a last bit that is not forced: the assertions
// are the special cases IEEE 754 fixes exactly, values whose correctly rounded result is the same
// under any implementation within an ulp of the truth, and identities that hold of the real
// cosine and so must hold of any faithful approximation to within a slack far wider than an ulp.
//
// The one place IEEE 754 leaves genuinely open is the payload of a NaN, whether generated by the
// domain error at an infinite argument or propagated from a NaN one: hosts differ on both the
// payload and the sign. So the NaN cases below check double.IsNaN and never the bits.
//
// The bit-exact specification of PawPrint's own answer, including the NaN payloads, lives in
// TestDeterministicMath.fs, which can assert it because it is not comparing against a host.
public static class MathCos
{
    // A spread of arguments covering every regime of the range reduction: below a quarter turn,
    // a few turns, and magnitudes at which no amount of double arithmetic can reduce the
    // argument and a multi-hundred-bit value of pi is the only way through.
    static readonly double[] Arguments =
    {
        0.0, 1e-300, 1e-30, 1e-8, 0.25, 0.5, 1.0, 1.5, 2.0, 3.0, 3.5, 6.0, 7.0,
        11.0, 123.456, 1000.0, 12345.6789, 1e5, 1e8, 1e10, 1e15, 1e20, 1e30,
        1e50, 1e100, 1e200, 1e300,
    };

    static int ExactCases()
    {
        // cos(±0) is exactly 1 under any implementation: there is nothing to round.
        if (Math.Cos(0.0) != 1.0) return 1;
        if (Math.Cos(-0.0) != 1.0) return 2;

        // And so is cos(x) for an x small enough that 1 - x^2/2 is nearer to 1 than to the
        // double below it: that needs x^2/2 below 2^-54, i.e. |x| below about 2^-26.
        if (Math.Cos(1e-30) != 1.0) return 3;
        if (Math.Cos(-1e-30) != 1.0) return 4;
        if (Math.Cos(1e-300) != 1.0) return 5;
        if (Math.Cos(double.Epsilon) != 1.0) return 6;

        return 0;
    }

    static int NaNRules()
    {
        // An infinite argument names no point on the circle: a domain error.
        if (!double.IsNaN(Math.Cos(double.PositiveInfinity))) return 1;
        if (!double.IsNaN(Math.Cos(double.NegativeInfinity))) return 2;

        // NaN propagates.
        if (!double.IsNaN(Math.Cos(double.NaN))) return 3;

        return 0;
    }

    static int StaysInRange()
    {
        for (int i = 0; i < Arguments.Length; i++)
        {
            double x = Arguments[i];
            double c = Math.Cos(x);

            if (double.IsNaN(c)) return 100 + i;
            if (c < -1.0 || c > 1.0) return 200 + i;

            // Evenness is required of the operation, not just of the real function it
            // approximates: IEEE 754-2019 clause 9.2 says so for every rounding attribute
            // over the whole domain. So both runtimes owe it exactly, not to within an ulp.
            if (Math.Cos(-x) != c) return 300 + i;
        }

        return 0;
    }

    static int DoubleAngleIdentity()
    {
        // cos(2x) = 2cos(x)^2 - 1 holds of the real cosine, so it must hold of any faithful
        // approximation to within a few ulps -- and doubling an argument is exact in binary
        // floating point, so the two sides really are the same real number.
        //
        // This is the strongest check available here, because it is the range reduction that
        // it tests: getting cos(1e20) right and cos(2e20) right *consistently* requires both
        // reductions to be against the same several-hundred-bit value of pi. An implementation
        // that reduced in double arithmetic would produce two unrelated numbers and fail by a
        // margin of order 1, not of order an ulp.
        for (int i = 0; i < Arguments.Length; i++)
        {
            // Every entry of Arguments is below 1e301, so 2x is representable throughout.
            double x = Arguments[i];
            double single = Math.Cos(x);
            double doubled = Math.Cos(2.0 * x);

            if (Math.Abs(doubled - (2.0 * single * single - 1.0)) > 1e-12) return 100 + i;
        }

        return 0;
    }

    static int DecreasesOverTheFirstHalfTurn()
    {
        // cos is strictly decreasing on [0, pi], and these samples are spaced far enough apart
        // that a one-ulp disagreement between implementations cannot reorder them.
        double previous = 2.0;

        for (int i = 0; i <= 32; i++)
        {
            double x = 3.14159265358979 * i / 32.0;
            double c = Math.Cos(x);

            if (c >= previous) return 100 + i;

            previous = c;
        }

        // ...and it has come essentially all the way down to -1 by the end.
        if (previous > -0.999) return 1;

        return 0;
    }

    public static int Main(string[] args)
    {
        int result;

        result = ExactCases();
        if (result != 0) return 1000 + result;

        result = NaNRules();
        if (result != 0) return 2000 + result;

        result = StaysInRange();
        if (result != 0) return 3000 + result;

        result = DoubleAngleIdentity();
        if (result != 0) return 4000 + result;

        result = DecreasesOverTheFirstHalfTurn();
        if (result != 0) return 5000 + result;

        return 0;
    }
}
