<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningLevel>0</WarningLevel>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <NoWarn>$(NoWarn);FS0025;FS0049;FS0064;FS3370;FS0064</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Implicit.fs" />
    <Compile Include="Census.fs" />
    <Compile Include="Escape.fs" />
    <Compile Include="Driver.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../WoofWare.PawPrint.Domain/WoofWare.PawPrint.Domain.fsproj" />
  </ItemGroup>
</Project>
